server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/** 
        - id: station
          uri: http://localhost:8083
          predicates:
            - Path=/managements/** 
        - id: mountpart
          uri: http://localhost:8084
          predicates:
            - Path=/mountParts/** 
        - id: stock
          uri: http://localhost:8085
          predicates:
            - Path=/stocks/** 
        - id: dashboard
          uri: http://localhost:8086
          predicates:
            - Path= /dashBoards/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, /order/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, /payment/**
        - id: station
          uri: http://station:8080
          predicates:
            - Path=/managements/**, management/**
        - id: mountpart
          uri: http://mountpart:8080
          predicates:
            - Path=/mountparts/**, /mountpart/**
        - id: stock
          uri: http://stock:8080
          predicates:
            - Path=/stocks/**, /stock/**
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path= /dashBoards/**, /dashBoard/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080